### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by DonghaiHan** [projectcontour/gimbal#272]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
in the first line: "Gimbal is a layer-7 load balancing platform built on Contour", the link associated with Contour is: https://vmware-tanzu.github.io/contour/, which is a 404

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment**:

- Gimbal Cluster Kubernetes version (use `kubectl version`):
- Backend Cluster versions (OpenStack and/or Kubernetes):
- Gimbal version (Gimbal git repository tag):
- Contour version:
- kubernetes-discoverer version:
- openstack-discoverer version (if applicable):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by stevesloka** [comment]
Thanks for reporting this @DonghaiHan, this was fixed in #273.

**Comment by DonghaiHan** [comment]
My pleasure @stevesloka
