### ISSUE TITLE
Image pull error

### ISSUE THREAD

**Issue by vsrivatsavr** [projectcontour/gimbal#275]
Trying to deploy Gimbal  using this 
https://github.com/vmware-tanzu/gimbal/blob/master/deployment/README.md

after  running "kubectl create -f contour/ " 
Contour pods are giving image pull error, when i tried to pull using docker pull got the below error:

docker pull gcr.io/vmware-tanzu-images/contour:v0.11.0
Error response from daemon: Get https://gcr.io/v2/vmware-tanzu-images/contour/manifests/v0.11.0: unknown: Project 'project:vmware-tanzu-images' not found or deleted.

Kube describe pod gives the below error

images/contour/manifests/v0.11.0: unknown: Project 'project:vmware-tanzu-images' not found or deleted.
  Warning  Failed     2m34s (x4 over 4m6s)  kubelet, ip-10-31-5-157.us-east-2.compute.internal  Error: ErrImagePull
  Normal   BackOff    2m20s (x7 over 4m6s)  kubelet, ip-10-31-5-157.us-east-2.compute.internal  Back-off pulling image "gcr.io/vmware-tanzu-images/contour:v0.11.0"

**Comment by jpeach** [comment]
@timh @stevesloka Do you know the status of Gimbal deployment images?

**Comment by stevesloka** [comment]
Hey @vsrivatsavr I need to fix those images, they are currently still hosted at: `projectcontour/contour:v0.11.0`. Also, that version is a bit old, so we should upgrade to the latest Contour image which is `v1.0.1`.

**Comment by stevesloka** [comment]
Hey, @vsrivatsavr I've updated the images, so all should work now. Please re-open this if you still have image issues. We'll update the image location soon, but for now, they still match what I referenced in the previous comment.
