### ISSUE TITLE
Update Envoy Prometheus Endpoint

### ISSUE THREAD

**Issue by stevesloka** [projectcontour/gimbal#81]
Envoy now adds a Prometheus endpoint `/stats/prometheus` that can be utilized. Need to update the deployment (https://github.com/heptio/gimbal/blob/master/deployment/contour/02-deployment.yaml#L21) to point to the new url.

**Comment by stevesloka** [comment]
This may want to wait until a new tagged version of Envoy is released. Right now tested on `latest` master build.

**Comment by xaleeks** [comment]
Is this still relevant? Can we close? @stevesloka
